const DEFAULT_FILTER = 'any';
const LOW_PRICE_FILTER = 10000;
const HIGH_PRICE_FILTER = 50000;
const CARDS_COUNT = 10;

const MAIN_PIN_LATITUDE = 35.66991;
const MAIN_PIN_LONGITUDE = 139.72887;

//форма объявления
const MIN_TITLE_LENGTH = 30;
const MAX_TITLE_LENGTH = 100;
const MAX_PRICE = 1000000;
const FILE_TYPES = ['jpg', 'jpeg', 'png'];
const DEFAULT_AVATAR = 'img/muffin-grey.svg';

export {
  DEFAULT_FILTER,
  LOW_PRICE_FILTER,
  HIGH_PRICE_FILTER,
  CARDS_COUNT,
  MAIN_PIN_LATITUDE,
  MAIN_PIN_LONGITUDE,
  MIN_TITLE_LENGTH,
  MAX_TITLE_LENGTH,
  MAX_PRICE,
  FILE_TYPES,
  DEFAULT_AVATAR
};
